name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: asdf_install
      uses: asdf-vm/actions/install@v1
    - name: Restore dependencies
      run: (cd src && dotnet restore)
    - name: Build
      run: (cd src && dotnet build --no-restore)
